import numpy as np
import os
import math
import argparse
import glob
import re

# This code prepares the annotations for fine-tuning SSD with different pedestrian datasets.
# The output detection annotation: label_id, xmin, ymin, xmax, ymax -->>  
# Refer to: https://github.com/weiliu89/caffe/issues/59
# This code conside only to class labels, 1 as person and 0 as background.

def ReadAnnotFile(filename):
	results = []
	labels = []
	f = open(filename)
	lines = f.read().splitlines()

	for l in lines[1: ]: # First line from annotations generated by caltech evaluation code is not annotation
		values = l.split(" ")
		labels.append(values[0])
		results.append( [float(i) for i in values[1:5]])
	
	return np.asarray(labels), np.asarray(results) 


if __name__ == "__main__":

	#Xmin = 0;
	#Ymin = 0;
	#Xmax = 639;
	#Ymax = 479;
	
	parser = argparse.ArgumentParser()
	parser.add_argument('-AnnotPath', help = 'Path to original annotations', required = True )
	parser.add_argument('-OutPath', help = 'Path to output annotations', required = True )

	args = vars(parser.parse_args())

	if args['AnnotPath'] is not None:
		in_path = args['AnnotPath']	
	if args['OutPath'] is not None:
		out_path = args['OutPath']


	for files in os.scandir(in_path):
		if files.is_file() and (files.name.endswith('.txt') ) :
			in_file_full_path = os.path.join(in_path, files.name) 
			out_file_full_path = os.path.join(out_path, files.name)

			labels, results = ReadAnnotFile(in_file_full_path)
			#f = open(out_file_full_path, 'ab')
			
			if labels.shape[0] == 0: # Background
				continue
				#det_person = np.atleast_2d( np.asarray([0 , Xmin, Ymin, Xmax, Ymax ] ) ) # [CLASS , DETS]
				#np.savetxt(f, det_person, fmt=["%d",]*5 , delimiter="," )
			else:
				f = open(out_file_full_path, 'ab')
				for idx, nm in enumerate(labels):
					det_person = np.atleast_2d( np.asarray([15 , max(0, results[idx,0]), max(0, results[idx,1]), max(0,results[idx,2]) + max(0,results[idx,0]), max(0,results[idx,3]) + max(0,results[idx,1]) ]) ) # [CLASS, DETS]		
					np.savetxt(f, det_person, fmt=["%d",]*1+["%f",]*4 , delimiter=" " )
				f.close()


